#!/usr/bin/env python3
"""Generate the Rust translation table from a gettext .po catalog.

Usage: gen-translations.py <catalog.po> <output.rs>

Emits a sorted static table of (msgid, msgstr) pairs plus a small accessor,
as the Rust side of the i18n layer (see src/util/i18n.rs). Entries with an
empty msgstr are skipped (untranslated strings fall back to the msgid).
"""

from __future__ import annotations

import sys
from pathlib import Path


def unescape(value: str) -> str:
    out = []
    index = 0
    while index < len(value):
        char = value[index]
        if char == "\\" and index + 1 < len(value):
            next_char = value[index + 1]
            mapped = {"n": "\n", "t": "\t", "r": "\r", '"': '"', "\\": "\\", "'": "'"}.get(
                next_char
            )
            if mapped is not None:
                out.append(mapped)
                index += 2
                continue
        out.append(char)
        index += 1
    return "".join(out)


def parse_po(path: Path) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    msgid: list[str] = []
    msgstr: list[str] = []
    section: str | None = None

    def flush() -> None:
        nonlocal msgid, msgstr, section
        if section == "msgstr":
            key = unescape("".join(msgid))
            value = unescape("".join(msgstr))
            if key and value:
                entries.append((key, value))
        msgid, msgstr, section = [], [], None

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("msgid "):
            flush()
            section = "msgid"
            msgid = [line[len("msgid ") :].strip('"')]
        elif line.startswith("msgstr "):
            section = "msgstr"
            msgstr = [line[len("msgstr ") :].strip('"')]
        elif line.startswith('"') and section in ("msgid", "msgstr"):
            (msgid if section == "msgid" else msgstr).append(line.strip('"'))
    flush()
    return entries


def rust_literal(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit("usage: gen-translations.py <catalog.po> <output.rs>")
    source, destination = Path(sys.argv[1]), Path(sys.argv[2])
    entries = parse_po(source)
    entries.sort()
    lines = [
        "//! GENERATED by tools/gen-translations.py — do not edit by hand.",
        "//! Source catalog: po/es.po (nextsync-py v0.4.0).",
        "",
        "/// Sorted (msgid, translation) pairs; lookup is a binary search.",
        "pub static CATALOG: &[(&str, &str)] = &[",
    ]
    for key, value in entries:
        lines.append(f"    ({rust_literal(key)}, {rust_literal(value)}),")
    lines.append("];")
    lines.append("")
    destination.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(entries)} entries -> {destination}")


if __name__ == "__main__":
    main()
